# Generated by Django 5.2.1 on 2025-06-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_external_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_group', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_since', models.DateTimeField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('last_order', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'indexes': [models.Index(fields=['email'], name='source_m_cu_email_77179e_idx'), models.Index(fields=['cpf'], name='source_m_cu_cpf_e99dbd_idx'), models.Index(fields=['cpf', 'email'], name='source_m_cu_cpf_2f5744_idx')],
            },
        ),
    ]
