# Generated by Django 5.2.1 on 2025-06-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source_m', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetail',
            new_name='BuyOrderDetail',
        ),
    ]
